$(document).ready(function(){
  $("#crewmatescreen").click(function(){
    $("#texttoggle").toggle();
  });
   $("#imposterscreen").click(function(){
    $("#texttoggle2").toggle();
  });
  $("#fadeclick").click(function(){
    $("#blackamong").fadeToggle();
    $("#brownamong").fadeToggle();
  });
});